# Generated by Django 4.1.5 on 2023-04-12 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue_Categor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('select_doctor', models.CharField(max_length=100)),
                ('appointment_time', models.CharField(choices=[('10:00 AM TO 11:00 AM', '10:00 AM TO 11:00 AM'), ('11:10 AM TO 12:00 PM', '11:10 AM TO 12:00 PM'), ('1:00 PM TO 2:00 PM', '1:00 PM TO 2:00 PM'), ('2:10 PM TO 3:00 PM', '2:10 PM TO 3:00 PM'), ('3:10 PM TO 4:00 PM', '3:10 PM TO 4:00 PM'), ('4:10 PM TO 5:00 PM', '4:10 PM TO 5:00 PM'), ('6:00 PM TO 7:00 PM', '6:00 PM TO 7:00 PM')], max_length=100)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.issue_categor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50)),
                ('experiance', models.CharField(max_length=50)),
                ('available', models.BooleanField()),
                ('appointment', models.CharField(choices=[('10:00 AM TO 11:00 AM', '10:00 AM TO 11:00 AM'), ('11:10 AM TO 12:00 PM', '11:10 AM TO 12:00 PM'), ('1:00 PM TO 2:00 PM', '1:00 PM TO 2:00 PM'), ('2:10 PM TO 3:00 PM', '2:10 PM TO 3:00 PM'), ('3:10 PM TO 4:00 PM', '3:10 PM TO 4:00 PM'), ('4:10 PM TO 5:00 PM', '4:10 PM TO 5:00 PM'), ('6:00 PM TO 7:00 PM', '6:00 PM TO 7:00 PM')], max_length=100)),
                ('image', models.ImageField(upload_to='doctor_image')),
                ('address', models.CharField(max_length=100)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.issue_categor')),
            ],
        ),
    ]
