# Generated by Django 4.1.5 on 2023-04-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue_Categor',
            new_name='Issue_Category',
        ),
    ]
